services:
  postgres:
    image: postgres:16-alpine
    container_name: goDrive
    environment:
      POSTGRES_USER: godrive_app
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: godrive
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U godrive_app -d godrive"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - godrive-network

  minio:
    image: minio/minio:latest
    container_name: godrive-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: godrive
      MINIO_ROOT_PASSWORD: change-me-strong-password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - godrive-network

volumes:
  postgres_data:
  minio_data:

networks:
  godrive-network:
    driver: bridge

